FROM --platform=$BUILDPLATFORM golang:1.21-alpine3.19 AS build
WORKDIR /app
COPY . /app
ARG TARGETOS TARGETARCH
ARG COIN_MARKET_CAP_API_KEY \
    EMAIL_SENDER_ADDRESS \
    EMAIL_SENDER_PASSWORD \ 
    POLYGON_KEY
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH
RUN go mod download && go mod verify
RUN go build -o /app/go-alert

FROM alpine:latest
WORKDIR /app
ARG COIN_MARKET_CAP_API_KEY \
    EMAIL_SENDER_ADDRESS \
    EMAIL_SENDER_PASSWORD
ENV COIN_MARKET_CAP_API_KEY=$COIN_MARKET_CAP_API_KEY \
    EMAIL_SENDER_ADDRESS=$EMAIL_SENDER_ADDRESS \
    EMAIL_SENDER_PASSWORD=$EMAIL_SENDER_PASSWORD \
    POLYGON_KEY=$POLYGON_KEY
COPY --from=build /app/go-alert /app
ENTRYPOINT [ "/app/go-alert"]
